#!/usr/bin/python3
import sys
from linuxmusterLinuxclient7 import environment, logging

if  len(sys.argv) != 2:
    logging.error("Usage: lmn-unset <key>=<value>")
    sys.exit(1)

status = environment.unset(sys.argv[1])
sys.exit(0 if status else 1)